### ISSUE TITLE
How to use  global_update_grad()?

### ISSUE THREAD

**Issue by cherrytora** [Yangfan-Jiang/Federated-Learning-with-Differential-Privacy-Technique#2]
Hello : )

I used global_update_grad() because I tried to playback the result in the original paper.
I'v already added epsilon and delta in class FLSever and fl_param, but it still ran an error like this ![image](https://user-images.githubusercontent.com/45777647/109822789-432bec00-7c72-11eb-9af8-5f5481bbe4e0.png)
Did I make a mistake or miss something?
Thank you !

**Comment by Yangfan-Jiang** [comment]
Hi, there are some bugs in the code. You can try it again with the latest version I just committed.

**Comment by Yangfan-Jiang** [comment]
Also, this code is not exactly reproduced according to any research papers, so be careful about some details (e.g., sensitivity compution, grad clipping). You may have to write these parts of the code yourself according to your needs.

**Comment by cherrytora** [comment]
I see.
Thanks for your reply and suggestion very much!
