### ISSUE TITLE
how to compute the sensitivity

### ISSUE THREAD

**Issue by hdadong** [Yangfan-Jiang/Federated-Learning-with-Differential-Privacy-Technique#3]
why your sensitivity =  2 * self.lr * self.clip / self.data_size + (self.E - 1) * 2 * self.lr * self.clip? in the paper ,the sensitivity = 2C*pi/m or 2C/m.

**Comment by Yangfan-Jiang** [comment]
![image](https://user-images.githubusercontent.com/31509709/110426001-47c42a80-80e0-11eb-905c-8b48a4c0808c.png)
- see issues #1(closed) and the comment :)
- this code is not exactly reproduced according to any research papers
