### ISSUE TITLE
how to preset (epsilon, delta) pair?

### ISSUE THREAD

**Issue by chenslcool** [Yangfan-Jiang/Federated-Learning-with-Differential-Privacy-Technique#4]
if I want to preset (epsilon, delta) pair as privacy guarantee, what should I do?
just modify FLClient.update, not change the sensivity, but modify new_param[name] += add guassian noise defined in gaussian_noise(), will it work?
I want to use the code of
`
def gaussian_noise()
`
Waht should I do? Recalculate the sensitivity?
Thanks!!!

**Comment by Yangfan-Jiang** [comment]
Yes, it works. You need compute the sensitivity according to some published papers.

However, `def gaussian_noise()` calculate the variance according to the basic definition of Gaussian Mechanism, which will **NOT** provide a **tight** DP bound.

Here are some papers about how to provide a tight upper bound on DP/Renyi-PD:
[1] Abadi, Martin, et al. "Deep learning with differential privacy." Proceedings of the 2016 ACM SIGSAC conference on computer and communications security. 2016.
[2] Mironov, Ilya, Kunal Talwar, and Li Zhang. "R\'enyi Differential Privacy of the Sampled Gaussian Mechanism." arXiv preprint arXiv:1908.10530 (2019).

In addition, "TensorFlow Privacy" (https://github.com/tensorflow/privacy) provides analysis tools for computing the privacy guarantees, which I think may be helpful.

**Comment by chenslcool** [comment]
thanks！
By the way,
What 'LS' in 'Gaussian noise for CDP-FedAVG-LS Algorithm' means?

**Comment by Yangfan-Jiang** [comment]
Low Sensitivity. It comes from an unpublished manuscript. 

I've modified the code of `def gaussian_noise`, please use the latest version. You can also use `def gaussian_noise_ls()` directly if you know how to compute the variance of gaussian noise to achieve (epsilon, delta)-DP.

**Comment by chenslcool** [comment]
thanks very much!

**Comment by mqchenliang** [comment]
By the way, when you running, waht's the version of pytorch, numpy and torchvision?
I met some bug in `def mnist_noniid(dataset, num_users):`
thanks!
